server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://sdp-1.cwbfz5zcys44.us-east-1.rds.amazonaws.com:5432/sdp-1
    username: postgres
    password: farakdadapeer
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
