server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practice_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
